language: c++
compiler:
  - gcc
os: linux
dist: bionic

addons:
  apt:
    packages:
      - libuv1-dev
      - libboost-all-dev
      - libssl-dev
      - rapidjson-dev
      - autoconf
      - openjdk-8-jdk-headless
      - maven
      - texlive-font-utils
      - python-six
      - lcov

before_install:
  - pip install --user cpp-coveralls

install: bash ./.travis/install-dependencies.sh

before_script: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';

env:
  - TEST_SUITE=travis-build.sh
  - TEST_SUITE=tsan-build.sh
  - TEST_SUITE=asan-build.sh

script: bash ./.travis/$TEST_SUITE

after_success:
  - bash ./.travis/coveralls-deploy.sh

